/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package examination;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JLabel;


    /**
 *
 * @author HP
 */
public class Cdtimer extends javax.swing.JFrame implements ActionListener 
{
protected String resfin=null;
    private static final long serialVersionUID = 1L;
    protected long count;
    private long timerStart;
    protected DateFormat dateFormat;
protected int flag=0;
    javax.swing.Timer timer = new javax.swing.Timer(1000, this);

    
    
    
    /**
     * Creates new form Cdtimer
     */
    public Cdtimer(int minutes, int seconds) {
       
        
        
        
        
        
        
        
        
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.MINUTE, minutes);
        cal.set(Calendar.SECOND, seconds);
        count = cal.getTime().getTime();

        dateFormat = new SimpleDateFormat("mm:ss");

        timer.start();
        timerStart = System.currentTimeMillis();
        long elapsedTime = System.currentTimeMillis()-timerStart;

        System.out.println(elapsedTime);

    }

    @Override
    public void actionPerformed(ActionEvent e)
    {
        // suppose to countdown till 00 MIN 00 SEC
        
      setText(dateFormat.format(count));
        count -= 1000;

        
        
        
          
        if (dateFormat.format(count).equalsIgnoreCase("00:00")) 
        {
        
        closewindow();
        
        
        }
            
            
            
            
            
            }
    public void closewindow()   
    {
timer.stop();
        setText("exam ended");
        estud3 es3=new estud3();
      resfin=es3.ansfield.getText();
      results ress=new results();
      ress.res2.setText(resfin);
        es3.rad1.setVisible(false);
        es3.rad2.setVisible(false);
        es3.rad3.setVisible(false);
        es3.rad4.setVisible(false);
        es3.box.setVisible(false);
        }

    private void setText(String format) {
        throw new UnsupportedOperationException("Not yet implemented");
    }
       
        
        
        
        
        
        
        
        
        
        
        
    
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cdtimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cdtimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cdtimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cdtimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Cdtimer(00,10).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
