/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package examination;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
import java.util.Enumeration;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
/**
 *
 * @author HP
 */
public class estud3 extends javax.swing.JFrame {

    ResultSet RS=null;
PreparedStatement PST=null;
Connection conn=null;
protected int x=1;
 int s=0;
int sum=0;
int cor=0;
int wrng=0;
public static String ssum="0";
String scor="0";
public static String swrng="0";
String a,b,c,d;
String ans="0";
String answ="0";
String ssum2="0";
char rin;
    public static String max;
    public int u=0;
    
    /**
     * Creates new form estud3
     */
    public estud3() {
        initComponents();
    conn=dbconnection.ConnectDb();

    setResizable(false);
    setLocationRelativeTo(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        box = new javax.swing.JTextArea();
        rad1 = new javax.swing.JRadioButton();
        rad2 = new javax.swing.JRadioButton();
        rad3 = new javax.swing.JRadioButton();
        rad4 = new javax.swing.JRadioButton();
        submit = new javax.swing.JButton();
        radinv = new javax.swing.JRadioButton();
        ansfield = new javax.swing.JTextField();
        wrongans = new javax.swing.JTextField();
        gudluck = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);

        box.setColumns(20);
        box.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        box.setLineWrap(true);
        box.setRows(5);
        box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(box);
        box.setWrapStyleWord(true);

        buttonGroup1.add(rad1);
        rad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rad2);

        buttonGroup1.add(rad3);

        buttonGroup1.add(rad4);

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam pics/play.png"))); // NOI18N
        submit.setText("START EXAM");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        radinv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radinvActionPerformed(evt);
            }
        });

        ansfield.setEditable(false);
        ansfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansfieldActionPerformed(evt);
            }
        });

        gudluck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam pics/Good-Luck-Free-Download-lllllPNG.png"))); // NOI18N

        alert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam pics/caution.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rad1)
                                        .addComponent(rad2)
                                        .addComponent(rad3)
                                        .addComponent(rad4))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(ansfield, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                                .addComponent(wrongans)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(407, 407, 407)
                                            .addComponent(radinv))))
                                .addComponent(alert)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(submit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(gudluck)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wrongans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(ansfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radinv))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rad1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rad2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rad3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rad4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(alert)
                .addGap(18, 18, 18)
                .addComponent(gudluck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        alert.setVisible(false);
        gudluck.setVisible(false);
        box.setEditable(false);
        
        //sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
//sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
//cd timer
     ansfield.setVisible(false);
        wrongans.setVisible(false);
        if(x==1)
{
     
        JFrame frame = new JFrame();
frame.setLocation(784,134);
frame.setUndecorated(true);
getRootPane().setWindowDecorationStyle(JRootPane.NONE);
frame.setAlwaysOnTop (true);
        frame.setTitle("Countdown Timer");
        frame.getContentPane().setBackground(Color.white);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setSize(190, 70);

        JPanel panel = new JPanel();
        JLabel label = new JLabel("Exam Timer: ");
        panel.add(label);

        
      ///get timer time from db table timer  
         try
        {
        String jk="Select time from timer where slno=1";    
            PST=conn.prepareStatement(jk);
            
            RS=PST.executeQuery();
            if(RS.next())
            {
        u=RS.getInt(1);
        CD k = new CD(00, u);
        frame.getContentPane().add(k);
        frame.setVisible(true);
        frame.getContentPane().add(panel);
        frame.setVisible(true);
            }
            else
            {
                
            }
        }
         catch(Exception e)
         {
             
         }
        
        
        
        
        
        
        //change timer value

      
        
        }
else
{
    
}

        

        
        
        
        
        
        
        
        
        
        
        
        
        
        
//sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
//sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
        
      box.setVisible(true);
      rad1.setVisible(true);
      rad2.setVisible(true);
      rad3.setVisible(true);
      rad4.setVisible(true);
      radinv.setVisible(false);
      //radinv.setEnabled(true);
      
      //x=1 code
        
        
        
       //radio silence 
         try
      {
    
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(null, e);
      }
        
        
         
   //here goes the calculate result part of the entire app
       
      if(x>=1 && x<=(s+1))
      {
        
      
         
         try{
         String answer="select ans from questions where slno=?";
         PST=conn.prepareStatement(answer);  
     PST.setString(1,String.valueOf(x-1));
       RS=PST.executeQuery();
       if(RS.next())
       {
            answ=RS.getString(1);
            //JOptionPane.showMessageDialog(null, answ);
            
            
            
            
            Enumeration<AbstractButton> bg=buttonGroup1.getElements();
         while(bg.hasMoreElements())
         {
             JRadioButton jrd=(JRadioButton) bg.nextElement();
             if (jrd.isSelected())
             {
                  ans=jrd.getText();
                 // JOptionPane.showMessageDialog(null, jrd.getText());
             }
         }
        if(answ.equals(ans))
        {
            sum=sum+1;
             ssum=String.valueOf(sum);
            ansfield.setText(ssum);
           
        }
           else
        {
          sum=sum+0; 
            ansfield.setText(ssum);
        }
       }
       else
       {
           
           
       }
         
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null, e);
         
     }
         
      }
      else
      {
          
      }
      
     
         
         
         
         
         //submit button start exam to next to finish
 try{
        String snosql="select max(slno) from questions";
        PST=conn.prepareStatement(snosql);
        RS=PST.executeQuery();
        
        if(RS.next())
   {
      s=RS.getInt(1);
      max=String.valueOf(s);
      wrongans.setText(max);
      
      
      //qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
      //code changed here
      //qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
      
      
      if(x>=1 && x<s)
        {   String m="Next";
            submit.setText(m);
        }
        
        
      else if(x==s)
        {
           String n="Finish";
            submit.setText(n); 
            
        }
      else
      {
          
      }
         
   
   }
        else
        {
            
        }

         }
         
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
             
         }
        
 if(x<=s)
 {
     
     
     
     
     
     
     
     
     try{
          String sql0="select qns from questions where slno=?";
        PST=conn.prepareStatement(sql0);  
     PST.setString(1,String.valueOf(x));
       RS=PST.executeQuery();
       if(RS.next())
       {
String a0=RS.getString(1);
box.setText(a0);
       }
       else
       {
           JOptionPane.showMessageDialog(null, "error");
       }
      }
       catch(Exception e){
       
           JOptionPane.showMessageDialog(null, e);
           
       }
       

     
     
     
     
     
     
     
     
     
     
     
     
     
       try{
          String sql1="select a from questions where slno=?";
        PST=conn.prepareStatement(sql1);  
     PST.setString(1,String.valueOf(x));
       RS=PST.executeQuery();
       if(RS.next())
       {
String a1=RS.getString(1);
rad1.setText(a1);
       }
       else
       {
           JOptionPane.showMessageDialog(null, "error");
       }
      }
       catch(Exception e){
       
           JOptionPane.showMessageDialog(null, e);
           
       }
       
       
       
       
       try{
          String sql2="select b from questions where slno=?";
        PST=conn.prepareStatement(sql2);  
     PST.setString(1,String.valueOf(x));
       RS=PST.executeQuery();
       if(RS.next())
       {
String a2=RS.getString(1);
rad2.setText(a2);
       }
       else
       {
           JOptionPane.showMessageDialog(null, "error");
       }
      }
       catch(Exception e){
       
           JOptionPane.showMessageDialog(null, e);
           
       }
       
       try{
          String sq3="select c from questions where slno=?";
        PST=conn.prepareStatement(sq3);  
     PST.setString(1,String.valueOf(x));
       RS=PST.executeQuery();
       if(RS.next())
       {
String a3=RS.getString(1);
rad3.setText(a3);
       }
       else
       {
           JOptionPane.showMessageDialog(null, "error");
       }
      }
       catch(Exception e){
       
           JOptionPane.showMessageDialog(null, e);
           
       }
       
       
       
       try{
          String sq4="select d from questions where slno=?";
        PST=conn.prepareStatement(sq4);  
     PST.setString(1,String.valueOf(x));
       RS=PST.executeQuery();
       if(RS.next())
       {
String a4=RS.getString(1);
rad4.setText(a4);
       }
       else
       {
           JOptionPane.showMessageDialog(null, "error");
       }
      }
       
       catch(Exception e){
       
           JOptionPane.showMessageDialog(null, e);
           
       } 
 }      
  else
 {
     
 }
 
 if(x>s){
                
            JOptionPane.showMessageDialog(this, "exam ended,Results will be displayed when the timer ends");
            box.setEnabled(false);
            rad1.setEnabled(false);
            rad2.setEnabled(false);
            rad3.setEnabled(false);
            rad4.setEnabled(false);
           alert.setVisible(true);
           submit.setVisible(false);
  //////////
            ///////////
            ////////////////
            // uncomment to bring up results right after finishing the exam
//               results g=new results();
//               g.setVisible(true);
//        ssum=Integer.toString(sum);
//         g.res2.setText(ssum);
//         cor=sum;
//         scor=Integer.toString(cor);
//         g.res3.setText(scor);
//         wrng=s-sum;
//         swrng=Integer.toString(wrng);
//         g.res4.setText(swrng);
//         
         
         
         
         
       
                
     }          
else
 {
     ansfield.setText(ssum);
     
     }
 
 
 
 
 
 
 //f.closewindow();
 
 
 
 
    
 
 
 x++;
buttonGroup1.clearSelection();        
     
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void radinvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radinvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radinvActionPerformed

    private void ansfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansfieldActionPerformed

        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ansfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
           
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(estud3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(estud3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(estud3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(estud3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                

                new estud3().setVisible(true);
           
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel alert;
    public javax.swing.JTextField ansfield;
    protected javax.swing.JTextArea box;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel gudluck;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JRadioButton rad1;
    protected javax.swing.JRadioButton rad2;
    protected javax.swing.JRadioButton rad3;
    protected javax.swing.JRadioButton rad4;
    protected javax.swing.JRadioButton radinv;
    protected javax.swing.JButton submit;
    protected javax.swing.JTextField wrongans;
    // End of variables declaration//GEN-END:variables
}
